package com.sample

import com.company.Main;
import com.company.Question;
import com.company.DroolsThread;
import com.company.Nutrient;
import com.company.Product;
import javafx.application.Platform;
import org.drools.runtime.StatefulKnowledgeSession;
import java.util.Arrays;


global Question question;
global DroolsThread droolsThread;

//objects
//sterowanie
//declare Start
//end

//rules
//sterowanie
rule "Init"
    when
    then
    	kcontext.getKnowledgeRuntime().getAgenda().getAgendaGroup( "initial" ).setFocus();
    	//insert(new Start());
end

rule "Question: Protein"
		agenda-group "initial"
    when
    then
        System.out.println( "Protein" );
        question.setQuestion("Zawartołł białka:",
        						Arrays.asList("Wysoka", "łrednia", "Niska", "Dowolna"),
        						droolsThread);
        insert(new Nutrient("Protein", question.getAnswer()));
end

rule "Question: Carbo"
		agenda-group "initial"
    when
    then
        System.out.println( "Carbo" );
        question.setQuestion("Zawartołł włglowodanłw:",
        						Arrays.asList("Wysoka", "łrednia", "Niska", "Dowolna"),
        						droolsThread);
        insert(new Nutrient("Carbohydrate", question.getAnswer()));
end

rule "Question: Fat"
		agenda-group "initial"
    when
    then
        System.out.println( "Fat" );
        question.setQuestion("Zawartołł tłuszczu:",
        						Arrays.asList("Wysoka", "łrednia", "Niska", "Dowolna"),
        						droolsThread);
        insert(new Nutrient("Fat", question.getAnswer()));
end

rule "Question: Calories"
		agenda-group "initial"
    when
    then
        System.out.println( "Kalorycznołł" );
        question.setQuestion("Kalorycznołł:",
        						Arrays.asList("Wysoka", "łrednia", "Niska", "Dowolna"),
        						droolsThread);
        insert(new Nutrient("Calories", question.getAnswer()));
end

rule "Question: Fiber"
		agenda-group "initial"
    when
    then
        System.out.println( "Fiber" );
        question.setQuestion("Zawartołł błonnika:",
        						Arrays.asList("Wysoka", "łrednia", "Niska", "Dowolna"),
        						droolsThread);
        insert(new Nutrient("Fiber", question.getAnswer()));
end

// TODO
rule "Nutrient: any value"
		salience 1
		agenda-group "initial"
	when
		n: Nutrient(Value("Dowolna"))
	then
		String name = n.getName();
		retract(n);
		for (String value : Arrays.asList("Wysoka", "łrednia", "Niska"))
		{
			insert(new Nutrient(name, value));
		}
end

rule "Makaron"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Makaron Pełnoziarnisty", false, true, false));
end

rule "Płatki owsiane"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("łrednia"))
	then
		insert(new Product("Płatki owsiane", false, true, false));
end

rule "Kurczak"
	when
		not Nutrient(Name("Miłso"), Value("nie"))
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Kurczak", true, false, false));
end

rule "łosoł"
	when
		not Nutrient(Name("Miłso"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"));
		(
			Nutrient(Name("Protein"), Value("łrednia"))
			or
			Nutrient(Name("Protein"), Value("Wysoka"))
		)
		Nutrient(Name("Fat"), Value("łrednia"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("łosoł", true, false, false));
end

rule "Fasola"
	when
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Fasola", false, false, false));
end

rule "Jajka"
	when
		Nutrient(Name("Calories"), Value("łrednia"))
		(
			Nutrient(Name("Protein"), Value("łrednia"))
			or
			Nutrient(Name("Protein"), Value("Wysoka"))
		)
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Jajka", false, false, false));
end

rule "Orzechy arachidowe"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Orzechy arachidowe", false, false, false));
end

rule "Banan"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Banan", false, false, false));
end

rule "Daktyle suszone"
	when
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Daktyle suszone", false, false, false));
end

rule "Jabłko"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Jabłko", false, false, false));
end

rule "Brokuły"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Brokuły", false, false, false));
end

rule "Dorsz"
	when
		not Nutrient(Name("Miłso"))
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Dorsz", true, false, false));
end

rule "Groszek zielony"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("łrednia"))
	then
		insert(new Product("Groszek zielony", false, false, false));
end

rule "Soja"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("łrednia"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Soja", false, false, false));
end

rule "Ziemniaki"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Ziemniaki", false, false, false));
end

rule "Kasza jaglana"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Kasza jaglana", false, false, false));
end

rule "Kasza jłczmienna"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("łrednia"))
	then
		insert(new Product("Kasza jaglana", false, true, false));
end

rule "Rył biały"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Rył biały", false, false, false));
end

rule "Rył brłzowy"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Rył brłzowy", false, false, false));
end

rule "Mleko"
	when
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Mleko", false, false, true));
end

rule "Mleko sojowe"
	when
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Mleko sojowe", false, false, false));
end

rule "Ser twarogowy chudy"
	when
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("Niska"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Ser twarogowy chudy", false, false, true));
end

rule "Ser twarogowy płtłusty"
	when
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Ser twarogowy płtłusty", false, false, true));
end

rule "Ser twarogowy tłusty"
	when
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("łrednia"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Ser twarogowy tłusty", false, false, true));
end

rule "Parmezan"
	when
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Parmezan", false, false, true));
end

rule "Włtroba wieprzowa"
	when
		not Nutrient(Name("Miłso"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Włtroba wieprzowa", true, false, false));
end

rule "Bataty"
	when
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("Niska"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Bataty", false, false, false));
end

rule "Kiełki ciecierzycy"
	when
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Kiełki ciecierzycy", false, false, false));
end

rule "Kiełki pszenicy"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Kiełki pszenicy", false, true, false));
end

rule "Migdały"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Migdały", false, false, false));
end

rule "Nasiona lnu"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("Wysoka"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("łrednia"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Nasiona lnu", false, false, false));
end

rule "Orzechy laskowe"
	when
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Wysoka"))
	then
		insert(new Product("Orzechy laskowe", false, false, false));
end

rule "Parłwki"
	when
		not Nutrient(Name("Miłso"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Parłwki", true, false, false));
end

rule "Włtrobianka"
	when
		not Nutrient(Name("Miłso"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Wysoka"))
		Nutrient(Name("Carbohydrate"), Value("Niska"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Włtrobianka", true, false, false));
end

rule "Bułki pszenne"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		Nutrient(Name("Calories"), Value("łrednia"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Bułki pszenne", false, true, false));
end

rule "Bułki mleczne"
	when
		not Nutrient(Name("Gluten"), Value("nie"))
		not Nutrient(Name("Laktoza"), Value("nie"))
		Nutrient(Name("Calories"), Value("Wysoka"))
		Nutrient(Name("Protein"), Value("łrednia"))
		Nutrient(Name("Fat"), Value("Niska"))
		Nutrient(Name("Carbohydrate"), Value("Wysoka"))
		Nutrient(Name("Fiber"), Value("Niska"))
	then
		insert(new Product("Bułki pszenne", false, true, true));
end

rule "Miłso"
		salience 1
	when
		not Nutrient(Name("Miłso"))
		p: Product(isMeat())
	then
		System.out.println("Miłso?");
		question.setQuestion("Miłso?", Arrays.asList("tak", "nie"), droolsThread);
        insert(new Nutrient("Miłso", question.getAnswer()));
        if(question.getAnswer() == "nie")
        	retract(p);
end

rule "Gluten"
		salience 1
	when
		not Nutrient(Name("Gluten"))
		p: Product(hasGluten())
	then
		question.setQuestion("Gluten?", Arrays.asList("tak", "nie"), droolsThread);
        insert(new Nutrient("Gluten", question.getAnswer()));
        if(question.getAnswer() == "nie")
        	retract(p);
end

rule "Laktoza"
		salience 1
	when
		not Nutrient(Name("Laktoza"))
		p: Product(hasLactose())
	then
		question.setQuestion("Laktoza?", Arrays.asList("tak", "nie"), droolsThread);
        insert(new Nutrient("Laktoza", question.getAnswer()));
        if(question.getAnswer() == "nie")
        	retract(p);
end

rule "GatherProducts"
		salience -1
	when
		p: Product()
	then
	    question.setResult(question.getResult()+p.Name() + "\n");
	    // + " &#10;"
		System.out.println(p.Name());
end

rule "NoProducts"
		salience -1
	when
		not Product()
	then
		System.out.println("Brak produktłw spełniajłcych podane kryteria");
end

rule "End"
		salience -2
    when
    then
        drools.halt();
        question.setEnd(true);
end

rule "AbruptEnd"
		salience 100
		auto-focus true
	when
		Nutrient( Name("End") )
	then
		drools.halt();
		System.out.println("Abrupt");
	end
